### PR TITLE
Enable beaker support for integration testing

### PR DESCRIPTION
**Pull request by cmhe**

### CODE REVIEW

**Comment by cmhe** [comment]
I currently get beaker or vagrant errors when trying to run beaker tests:

```
$ bundle exec rake beaker:debian-8-amd64-vagrant
TEST_TIERS env variable not defined. Defaulting to run all tests.
/home/ch/.rbenv/versions/2.7.6/bin/ruby -I/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib:/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.11.0/lib /home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/exe/rspec spec/acceptance
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/specinfra-2.82.2/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Hypervisor for debian-8-amd64 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create
created Vagrantfile for VagrantHost debian-8-amd64
Failed to exec 'vagrant up'. Error was /usr/lib/ruby/vendor_ruby/rubygems.rb:265:in `find_spec_for_exe': can't find gem vagrant (>= 0.a) with executable vagrant (Gem::GemNotFoundException)
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:284:in `activate_bin_path'
        from /usr/bin/vagrant:25:in `<main>'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:274:in `block (2 levels) in vagrant_cmd'
/home/ch/.rbenv/versions/2.7.6/lib/ruby/2.7.0/open3.rb:219:in `popen_run'
/home/ch/.rbenv/versions/2.7.6/lib/ruby/2.7.0/open3.rb:101:in `popen3'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:268:in `block in vagrant_cmd'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:265:in `chdir'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:265:in `vagrant_cmd'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-vagrant-0.7.1/lib/beaker/hypervisor/vagrant.rb:252:in `provision'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/hypervisor.rb:37:in `create'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/network_manager.rb:72:in `block in provision'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/network_manager.rb:71:in `each_key'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-4.37.1/lib/beaker/network_manager.rb:71:in `provision'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/beaker-rspec/beaker_shim.rb:35:in `provision'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/beaker-rspec/spec_helper.rb:57:in `block in <top (required)>'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core.rb:98:in `configure'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/beaker-rspec.rb:5:in `require'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/
beaker-rspec.rb:5:in `<module:BeakerRSpec>'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/
beaker-rspec.rb:1:in `<top (required)>'
/home/ch/Projects/puppet-pam_pkcs11/spec/spec_helper_acceptance.rb:1:in `require'
/home/ch/Projects/puppet-pam_pkcs11/spec/spec_helper_acceptance.rb:1:in `<top (required)>'
/home/ch/Projects/puppet-pam_pkcs11/spec/acceptance/init_spec.rb:1:in `require'
/home/ch/Projects/puppet-pam_pkcs11/spec/acceptance/init_spec.rb:1:in `<top (required)>'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2115:in `load'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2115:in `load_file_handling_errors'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:1615:in `block in load_spec_files'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:1613:in `each'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:1613:in `load_spec_files'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:102:in `setup'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:86:in `run'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/exe/rspec:4:in `<main>'
/home/ch/.rbenv/versions/2.7.6/bin/ruby -I/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib:/home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.11.0/lib /home/ch/Projects/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/exe/rspec spec/acceptance failed
```

I am currently not sure why this happens... Vagrant works on its own, and it also worked when doing testing with kitchen. So its possible some issue with beaker...

**Comment by cmhe** [comment]
I reproduced the issue with the quick start project inside a virtualbox/vagrant machine and reported the issue here: https://github.com/voxpupuli/beaker/issues/1752

**Comment by cmhe** [comment]
It seems the issue is with trying to start beaker with `bundler exec`. beaker seems to work when called directly... I will have to investigate how to best integrate this here now.

**Comment by cmhe** [comment]
> It seems the issue is with trying to start beaker with `bundler exec`. beaker seems to work when called directly... I will have to investigate how to best integrate this here now.

However this currently also fails, because of the following error:

```
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

which happens inside the virtualbox where the nested virtual box should be configured.

**Comment by cmhe** [comment]
> > It seems the issue is with trying to start beaker with `bundler exec`. beaker seems to work when called directly... I will have to investigate how to best integrate this here now.
> 
> However this currently also fails, because of the following error:
> 
> ```
> VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
> ```
> 
> which happens inside the virtualbox where the nested virtual box should be configured.

So this issue happens because virtual box limits which subnets are allowed to be created. Adding the `10.255.x.x` subnet is possible: https://www.virtualbox.org/manual/ch06.html#network_hostonly

**Comment by cmhe** [comment]
I tried with `vagrant-wrapper`, but that also does not seem to work. Using that, the process gets stuck:

```
$ bundle exec rake beaker:debian-8-amd64-vagrant
TEST_TIERS env variable not defined. Defaulting to run all tests.
/home/vagrant/.rbenv/versions/2.7.6/bin/ruby -I/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib:/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.11.0/lib /project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/exe/rspec spec/acceptance
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/beaker-rspec-7.1.0/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/specinfra-2.82.2/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Hypervisor for debian-8-amd64 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create

^Crake aborted!
Interrupt:
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/rake_task.rb:97:in `system'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/rake_task.rb:97:in `run_task'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/rake_task.rb:116:in `block (2 levels) in define'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/rake_task.rb:114:in `block in define'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.11.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.11.0/lib/honeycomb/client.rb:65:in `start_span'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.11.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/puppetlabs_spec_helper-3.0.0/lib/puppetlabs_spec_helper/tasks/beaker.rb:107:in `block (2 levels) in <top (required)>'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.11.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.11.0/lib/honeycomb/client.rb:65:in `start_span'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.11.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/project/puppet-pam_pkcs11/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/vagrant/.rbenv/versions/2.7.6/bin/bundle:23:in `load'
/home/vagrant/.rbenv/versions/2.7.6/bin/bundle:23:in `<main>'
Tasks: TOP => beaker
(See full trace by running task with --trace)
```

**Comment by cmhe** [comment]
For reference I looked into what other PDK based layers do for acceptance testing, and it seems like beaker is no longer used and instead they use [litmus](https://puppetlabs.github.io/litmus/).

**Comment by mlegner** [comment]
> For reference I looked into what other PDK based layers do for acceptance testing, and it seems like beaker is no longer used and instead they use [litmus](https://puppetlabs.github.io/litmus/).

That looks quite interesting from the few examples they include. Maybe something for the future.

**Comment by mlegner** [comment]
@cmhe You've requested a review; should I try running beaker on my system?

**Comment by cmhe** [comment]
> @cmhe You've requested a review; should I try running beaker on my system?

I just added you as a reviewer, because I am not sure if you are getting notifications when I post something here otherwise. I real review should be done when I actually remove the draft status, IMO.

> That looks quite interesting from the few examples they include. Maybe something for the future.

Well... The real question is, which I haven't really figured out yet, what the way of the least resistance with acceptance testing is. With beaker stuff seems to have changed somewhat and it will require rewriting the test code. Also it is not really clear to me how everything fits together. So maybe it might be better to just switch over to litmus and learn to deal with that...

The documentation of litmus looks better and is more clear to me how it works than the one with beaker, however with litmus just provisioning docker images [doesn't seems to work](https://github.com/puppetlabs/puppet_litmus/issues/442), and I also have not gotten provisioning of vagrant images to work yet, because either it cannot find the `vagrant` executable or, when using `vagrant-wrapper` it seems to get stuck without any logs.

**Comment by mlegner** [comment]
> I just added you as a reviewer, because I am not sure if you are getting notifications when I post something here otherwise. I real review should be done when I actually remove the draft status, IMO.

Thanks. :smiley: I've subscribed to the whole repository, so I get notified in any case.

> The real question is, which I haven't really figured out yet, what the way of the least resistance with acceptance testing is. 

If just getting beaker to work again is so tedious, it might make more sense to directly adopt the currently used/recommended system. Difficult for me to judge, though.

**Comment by cmhe** [comment]
@mlegner: I opened #8, which enables litmus and acceptance testing seems to work there again. I could not get it to work on my system however, but at least it works on github now.

If you agree we can close this PR.

**Comment by mlegner** [comment]
> @mlegner: I opened #8, which enables litmus and acceptance testing seems to work there again. I could not get it to work on my system however, but at least it works on github now.
> 
> If you agree we can close this PR.

Sounds good, I'll take a closer look at #8 then.

**Pull request closed without merging**
