### PR TITLE
chore: remove outdated tests

### PR DESCRIPTION
**Pull request by mlegner**

### CODE REVIEW

**Comment by nsballmann** [comment]
Just for my understanding:

This drops Debian 7 and 8 as well as Ubuntu 12.04 and 14.04 and RHEL-5 (32+64bit) support. Treats Debian 9 and 10 as well as Ubuntu 18.04 and 20.04 as legacy/old systems. Debian 11 and Ubuntu 22.04 are becoming the main focus.

Additionally it adapts the lib paths to the "new" paths in what the tests expect from the package.

Correct?

**Comment by mlegner** [comment]
> This drops Debian 7 and 8 as well as Ubuntu 12.04 and 14.04 and RHEL-5 (32+64bit) support. Treats Debian 9 and 10 as well as Ubuntu 18.04 and 20.04 as legacy/old systems. Debian 11 and Ubuntu 22.04 are becoming the main focus.

The old Debian and Ubuntu systems were already unsupported before (officially), this PR just removes the tests as well.

The naming "Debian-old" is somewhat arbitrary, this is just to distinguish the expected results of different Debian "generations". But yes, the target distributions are Debian 11 and Ubuntu Jammy.

> Additionally it adapts the lib paths to the "new" paths in what the tests expect from the package.

Yes. Although the diff view is a bit misleading: In practice I just deleted `Debian-old`, then renamed `Debian` to `Debian-old`, then renamed `Debian11` to `Debian`.

**Comment by nsballmann** [comment]
Understood. Yes, I might have expressed myself a little too brief. :slightly_smiling_face: 

Yes, I somehow also noticed the generational thing with the oldest generation going out of the door and every newer generation getting one step closer to that door.  :smiley_cat:

**Review by nsballmann — APPROVED** [review]
LGTM :ok_hand:

**Pull request merged**
