### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by mlegner**

### CODE REVIEW

**Comment by nsballmann** [comment]
Can I simply rely on the fact that the tests are green to approve this?

**Comment by mlegner** [comment]
> Can I simply rely on the fact that the tests are green to approve this?

Yes. :grinning:

**Review by nsballmann — APPROVED** [review]
LGTM :ok_hand:

**Comment by mlegner** [comment]
@goko Could you take a look and merge this PR if you are satisfied?

**Pull request merged**
