### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by cmhe**

### CODE REVIEW

**Comment by cmhe** [comment]
@mlegner: I guess we should at some point make a release of this. If we want to release to puppetforge we would also need a API key.

**Comment by mlegner** [comment]
@cmhe That makes sense. Merging this would trigger the GitHub "release" workflow, is that right?

Did you make the changes to the `README.md` file manually or using some tool?

Concerning the Puppet Forge: I don't think this is too urgent at the moment as long as we can consume the module from GitHub. What do you think, @bufferoverflow?

**Comment by bufferoverflow** [comment]
> @cmhe That makes sense. Merging this would trigger the GitHub "release" workflow, is that right?
> 
> Did you make the changes to the `README.md` file manually or using some tool?
> 
> Concerning the Puppet Forge: I don't think this is too urgent at the moment as long as we can consume the module from GitHub. What do you think, @bufferoverflow?

Yes, let's do that at a later step and start using it first via github.

**Comment by cmhe** [comment]
The currently used github action [`release.yml`](https://github.com/siemens/puppet-pam_pkcs11/blob/main/.github/workflows/release.yml) is generated from the pdk template [`release.yml.erb`](https://github.com/puppetlabs/pdk-templates/blob/main/moduleroot/.github/workflows/release.yml.erb), which doesn't offer a way to disable the puppet forge push step.

So if we don't want to push to puppet forge, then we will need our own release.yml. I will have to investigate how to disable the template generation for just the `release.yml` file.

When I discussed the acceptance test integration with the people from the beaker project, they mentioned that [PDK makes things difficult in advanced cases](https://github.com/voxpupuli/beaker/issues/1752#issuecomment-1203817237), so they try to stay away from the PDK. In my experience so far that starts to ring true, however it is the 'offical' way to develop puppet modules. So I try to stay away from doing anything special here and go with the flow as much as possible. IMO similar to the Honeycomb integration, if it is easier to just create a Honeycomb/Puppetforge account and let the CI dump some data there even if it doesn't make much sense, then removing the Honeycomb/Puppetforge integration, then I would go with creating those accounts...

**Comment by mlegner** [comment]
If it's less work to publish it on Forge than *not* doing it, I agree that it makes sense.

If we want to publish this on Forge properly, we should probably create a "Siemens" account.

WDYT, @bufferoverflow?

**Comment by cmhe** [comment]
> If it's less work to publish it on Forge than _not_ doing it, I agree that it makes sense.

That is to be determined still. I never published something on forge. But I imagine that it is just about creating an account, adding the API key to the repo and then pressing the 'trigger release' button somewhere on github.

The main advantage is that we stay with what PDK desires and hopefully in the long run makes managing the project easy, because the PDK devs take care of making everything work instead of us.

**Comment by mlegner** [comment]
I'm closing this for now as we don't want to publish this to the Puppet Forge at the moment.

**Pull request closed without merging**
